### ISSUE TITLE
Tracking today workout list

### ISSUE THREAD

**Issue by praveenraam** [praveenraam/RN-Workout_Tracker#4]
- [x] Get today's workout Detail
- [x] Display 
- [x] Style
- [x] Store the today's workout
- [x] Get the workout's muscle name
- [x] Display the today's workout
- [x] Eliminate the duplicate workouts
- [x] Button to refresh the component

**Comment by praveenraam** [comment]
## Error rised in [Commit](https://github.com/praveenraam/RN-Workout_Tracker/commit/f278c469e37932b0fb9f05c344158a0db590c1ab)

After removing the Temporary workout json, we need to fetch the data from the Async Storage

**Comment by praveenraam** [comment]
- Need to eliminate the duplicate elements

**Comment by praveenraam** [comment]
## Code for this component is done
![Image](https://github.com/user-attachments/assets/bdc5fc8e-0661-4e9d-aa95-51183c81d148)
